#!/bin/bash

sed -i 's/\r//' script-ex5

PERSON1=$1
PERSON2=$2

echo "${PERSON1}:: Hi ${PERSON2}, how are you?"
echo "${PERSON2}:: Hello ${PERSON1}, i am fine. what are doing?"
echo "${PERSON1}:: I started new project."