#!/bin/bash
sed -i 's/\r//g' script-ex2

STATES=("Telanagana" "Kerla" "AP" "UP")

echo "Print first state is: ${STATES[0]}"
echo "Print Second state is: ${STATES[1]}"
echo "Print Third state is: ${STATES[2]}"

echo "Print total states are: ${STATES[@]}"





