#!/bin/bash
# PERSON1=Hari
# PERSON2=DAs

# echo "$PERSON1:: Hi $PERSON2, How r u?"
# echo "$PERSON2:: Hi $PERSON1, iam good. How about u?"
# echo "$PERSON1:: I am fine. How is your going."
# echo "$PERSON2:: Doing good as of now."

PERSON1=Rakesh
PERSON2=Ravi

echo "$PERSON1:: Hi $PERSON2, how are you ?"
echo "$PERSON2:: Hi $PERSON1, i am good how about you."
echo "$PERSON1:: I am doing fine, how your work is going."
echo "$PERSON2:: Its Going good."
