#!/bin/bash


#if [ $? -ne 0 ]
#then
 #   echo "Statement is true"
#else
 #   echo "Statement is false"
#fi

#Ex-2
TODAY=$1

if ($TODAY -eq "Monday" $TODAY -eq "Tue" $TODAY -eq "Wed" $TODAY -eq "Thu" $TODAY -eq "Fri")
then
    echo "there is class to attend"
else
    echo "There is no class to attend"
fi   