#!/bin/bash


#if [ $? -ne 0 ]
#then
 #   echo "Statement is true"
#else
 #   echo "Statement is false"
#fi

#Ex-2
#!/bin/bash

# Get the current day of the week (1-7, where 1 is Monday and 7 is Sunday)
#day_of_week=$(date +%u)

# Check if the day is Monday to Friday (1 to 5)
#if [ "$day_of_week" -ge 1 ] && [ "$day_of_week" -le 5 ]; then
 #   echo "There is a class today."
#else
 #   echo "No class today."
#fi

day_of_week=$(date +%u)

if [ $day_of_week -eq 2 ]
then
    echo "There is a class today."
else
    echo "No class today."
fi
   