#!/bin/bash

PERSON1=Ram
PERSON2=Ramesh

Age=$1

if [ $Age -gt 20 ]
then
    echo "age of $PERSON1 is greater than 20"
else
    echo  "age of $PERSON1 is less than 20"
fi

if [ $Age -lt 25 ]
then
    echo "age of $PERSON2 is less than 25"
else
    echo "age of $PERSON2 is greater than 25"    
fi     