#!/bin/bash

Userid=$(id -u)
 echo "user id is: $Userid"

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

CHECK_ROOT(){
    if [ $Userid -ne 0 ]
    then
       echo "please login with root previleges"
       exit 1
    fi   
}

VALIDATE(){
    if [ $1 -ne 0 ]
    then
        echo -e "$2 is ... $R Failed $N"
        exit 1
    else
        echo -e "$2 is ... $G Success $N"
    fi        
}

CHECK_ROOT()

for package in $@
do
    dnf list installed $package
    if [ $? -ne 0 ]
    then
        echo "$package is not installed..going to install"
        dnf install $package -y
        VALIDATE $? "Installing $package"
    else
        echo "$package  is alraedy installed...Nothing to do"
    fi      
done 
