#!/bin/bash


#if [ $? -ne 0 ]
#then
 #   echo "Statement is true"
#else
 #   echo "Statement is false"
#fi

#Ex-2


if (TODAY= "Mon" "Tue" "Wed" "Thu" "Fri")
then
    echo "there is class to attend"
else
    echo "There is no class to attend"
fi       