#!/bin/bash
PERSON1=Hari
PERSON2=Das

echo "$PERSON1:: Hi $PERSON2, how are you?"
echo "$PERSON2:: Hello $PERSON1, iam doing good.how about you?"
echo "$PERSON1:: Going fine as of now $PERSON2, how is your work."

