#!/bin/bash
PERSON1=Hari
PERSON2=Das

echo "$PERSON1:: Hi $PERSON2, How r u?"
echo "$PERSON2:: Hi $PERSON1, iam good. How about u?"
echo "$PERSON1:: I am fine. How is your going."
echo "$PERSON2:: Doing good as of now."
